version: "3"
services:
  backend:
    container_name: workgo-node-backend
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app # Mount the current directory into /usr/src/app inside the container
    env_file:
      - .env
    depends_on:
      - postgres # Ensures PostgreSQL starts before Node.js app
    command: >
      sh -c "if [ \"$NODE_ENV\" = 'development' ]; then npm run docker:dev; else npm start; fi"

  postgres:
    image: postgres:13 # PostgreSQL version 13
    ports:
      - "5432:5432" # Map port 5432 on the host to port 5432 on the container
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data # Persist database data

volumes:
  pgdata:
